#!/bin/bash
#
# Build DMG with dmgbuild. The volume name and file name are set in
# dmgbuild_settings.py so the command line values are dummies.
#
dmgbuild -s $GITHUB/IV_Swinger/build_tools/dmgbuild_settings.py \
         "XXXX" XXXX.dmg
