#!/bin/bash
#
#             % mac_run_pyi
#
pyinstaller --windowed \
            --noconfirm \
            --icon="$GITHUB/IV_Swinger/icons/IV_Swinger2.icns" \
            --add-data="$GITHUB/IV_Swinger/python3/Splash_Screen.png:." \
            --add-data="$GITHUB/IV_Swinger/python3/Blank_Screen.png:." \
            --add-data="$GITHUB/IV_Swinger/python3/version.txt:." \
            --name "IV Swinger 2" \
            $GITHUB/IV_Swinger/python3/IV_Swinger2_gui.py
$GITHUB/IV_Swinger/build_tools/fix_info_plist.py ./dist/IV\ Swinger\ 2.app/Contents/Info.plist
