#!/bin/bash
pyinstaller --windowed \
            --noconfirm \
            --icon="$GITHUB/IV_Swinger/icons/IV_Swinger2.icns" \
            --add-data="$GITHUB/IV_Swinger/python/Splash_Screen.png:." \
            --name "IV Swinger 2" \
            $GITHUB/IV_Swinger/python/IV_Swinger2.py
